// Fake quote system. Newspapers run reaction quotes; ours invents them for comic
// effect, attributed to league TEAMS (resolved per-week by name) or anonymous
// "league sources." Football-only: quotes are about lineups, losses, trades, luck —
// never real slurs or personal content, regardless of the team's name.
//
// These are generated by the LLM (so they vary every issue), but this module
// defines the ROLES a quote can play and picks which teams get quoted, so quotes
// are always tied to something that actually happened in the data.

// Decide who gets quoted this week and in what role, from the week's facts.
// Returns quote "slots" the writer fills — each tied to a real event.
export function planQuotes(facts, identity) {
  const slots = [];

  // 1) The blowout loser — defiant or in denial.
  if (facts.biggestBlowout) {
    slots.push({
      role: 'defiant_loser',
      subject: facts.biggestBlowout.loser,
      name: identity.nameOf(facts.biggestBlowout.loser),
      context: `lost by ${facts.biggestBlowout.margin} this week`,
      guidance: 'A defensive, in-denial, or defiant one-liner about the loss. Blame the bench, the projections, variance — anything but themselves.',
    });
  }

  // 2) The bench criminal — caught leaving points on the bench.
  if (facts.topBenchCrime) {
    slots.push({
      role: 'bench_criminal',
      subject: facts.topBenchCrime.roster_id,
      name: identity.nameOf(facts.topBenchCrime.roster_id),
      context: `left ${facts.topBenchCrime.left} points on the bench`,
      guidance: 'A cope quote rationalizing the lineup decision. "I had a feeling", "trusting the process", etc.',
    });
  }

  // 3) Anonymous league source — for the rumor mill (positional need).
  if (facts.topRumor) {
    slots.push({
      role: 'anon_source',
      subject: facts.topRumor.roster_id,
      name: identity.nameOf(facts.topRumor.roster_id),
      context: `thin at ${facts.topRumor.position}`,
      guidance: 'An ANONYMOUS "league source" whispering about this team shopping for help. Never a direct quote from the team — always "a source familiar with...".',
    });
  }

  // 4) The smug winner — the top scorer, insufferable about it.
  if (facts.topScorer) {
    slots.push({
      role: 'smug_winner',
      subject: facts.topScorer.roster_id,
      name: identity.nameOf(facts.topScorer.roster_id),
      context: `posted the week's high score of ${facts.topScorer.points}`,
      guidance: 'A short, insufferably smug victory quote. Trash talk aimed at the league in general, football-only.',
    });
  }

  return slots;
}

// The writer prompt fragment for generating the quotes.
export function quotePrompt(slots, persona) {
  return `Invent ONE short fake quote for each slot below, as ${persona.name} would
plant them in the paper. Rules:
- Attribute team quotes to the team NAME given (verbatim).
- Football-only: about lineups, losses, trades, luck, trash talk. Never reference the
  literal meaning of any team name; never personal/real-world insults.
- Keep each quote under 25 words. Make them funny, in-character for a trash-talking
  fantasy league. Vary them — no two should sound alike.
- For 'anon_source', DON'T name the team as the speaker; phrase as an unnamed source.

SLOTS:
${JSON.stringify(slots, null, 2)}

Return JSON: [{ "role": "...", "attribution": "...", "quote": "..." }]`;
}
